source 'https://github.com/CocoaPods/Specs.git'

target 'HaidoraAlertViewManager_Example', :exclusive => true do
  pod "HaidoraAlertViewManager", :path => "../"
end

target 'HaidoraAlertViewManager_Tests', :exclusive => true do
  pod "HaidoraAlertViewManager", :path => "../"

  
end
